# Generated by Django 6.1.1 on 2026-09-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
